# Dockerfile para la base de datos MariaDB
# ----------------------------------------
# Comentario: Usamos una imagen oficial de MariaDB como base
FROM mariadb:11.1

# Comentario: Establecemos las variables de entorno necesarias para crear la base de datos y usuario
# ENV MARIADB_DATABASE=gestion \
#     MARIADB_USER=root \
#     MARIADB_PASSWORD=dan007 \
#     MARIADB_ROOT_PASSWORD=dan007

# Comentario: Exponemos el puerto 3306 para conexiones externas
EXPOSE 3306
